# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/config.schema.json
source: /home/lcr/.config/skillshare/skills
mode: copy
targets:
  claude:
    skills:
      path: /home/lcr/.claude/skills
  opencode:
    skills:
      path: /home/lcr/.config/opencode/skills
  universal:
    skills:
      path: /home/lcr/.agents/skills
ignore:
  - '**/.DS_Store'
  - '**/.git/**'
audit:
  block_threshold: CRITICAL
tui: false
