graph TD
    N0[activate_this.py]
    N1[__init__.py]
    N2[config_analyzer.py]
    N3[main.py]
    N4[demo_conflicts.py]
    N5[test_http_server.py]
    N6[__init__.py]
    N7[__init__.py]
    N8[__init__.py]
    N9[base.py]
    N10[claude.py]
    N11[gemini.py]
    N12[markdown.py]
    N13[openai.py]
    N14[ai_enhancer.py]
    N15[api_reference_builder.py]
    N16[architectural_pattern_detector.py]
    N17[code_analyzer.py]
    N18[codebase_scraper.py]
    N19[config_command.py]
    N20[config_enhancer.py]
    N21[config_extractor.py]
    N22[config_manager.py]
    N23[config_validator.py]
    N24[conflict_detector.py]
    N25[constants.py]
    N26[dependency_analyzer.py]
    N27[doc_scraper.py]
    N28[enhance_skill.py]
    N29[enhance_skill_local.py]
    N30[enhance_status.py]
    N31[estimate_pages.py]
    N32[generate_router.py]
    N33[github_fetcher.py]
    N34[github_scraper.py]
    N35[guide_enhancer.py]
    N36[how_to_guide_builder.py]
    N37[install_agent.py]
    N38[install_skill.py]
    N39[language_detector.py]
    N40[llms_txt_detector.py]
    N41[llms_txt_downloader.py]
    N42[llms_txt_parser.py]
    N43[main.py]
    N44[markdown_cleaner.py]
    N45[merge_sources.py]
    N46[package_multi.py]
    N47[package_skill.py]
    N48[pattern_recognizer.py]
    N49[pdf_extractor_poc.py]
    N50[pdf_scraper.py]
    N51[quality_checker.py]
    N52[rate_limit_handler.py]
    N53[resume_command.py]
    N54[run_tests.py]
    N55[setup_wizard.py]
    N56[split_config.py]
    N57[swift_patterns.py]
    N58[test_example_extractor.py]
    N59[test_unified_simple.py]
    N60[unified_codebase_analyzer.py]
    N61[unified_scraper.py]
    N62[unified_skill_builder.py]
    N63[upload_skill.py]
    N64[utils.py]
    N65[__init__.py]
    N66[agent_detector.py]
    N67[git_repo.py]
    N68[server.py]
    N69[server_fastmcp.py]
    N70[server_legacy.py]
    N71[source_manager.py]
    N72[__init__.py]
    N73[config_tools.py]
    N74[packaging_tools.py]
    N75[scraping_tools.py]
    N76[source_tools.py]
    N77[splitting_tools.py]
    N78[test_api.py]
    N79[__init__.py]
    N80[conftest.py]
    N81[__init__.py]
    N82[test_adaptors_e2e.py]
    N83[test_base.py]
    N84[test_claude_adaptor.py]
    N85[test_gemini_adaptor.py]
    N86[test_markdown_adaptor.py]
    N87[test_openai_adaptor.py]
    N88[test_api_reference_builder.py]
    N89[test_architecture_scenarios.py]
    N90[test_async_scraping.py]
    N91[test_bootstrap_skill.py]
    N92[test_bootstrap_skill_e2e.py]
    N93[test_c3_integration.py]
    N94[test_cli_paths.py]
    N95[test_code_analyzer.py]
    N96[test_codebase_scraper.py]
    N97[test_config_extractor.py]
    N98[test_config_validation.py]
    N99[test_constants.py]
    N100[test_dependency_analyzer.py]
    N101[test_e2e_three_stream_pipeline.py]
    N102[test_estimate_pages.py]
    N103[test_excluded_dirs_config.py]
    N104[test_generate_router_github.py]
    N105[test_git_repo.py]
    N106[test_git_sources_e2e.py]
    N107[test_github_fetcher.py]
    N108[test_github_scraper.py]
    N109[test_guide_enhancer.py]
    N110[test_how_to_guide_builder.py]
    N111[test_install_agent.py]
    N112[test_install_multiplatform.py]
    N113[test_install_skill.py]
    N114[test_install_skill_e2e.py]
    N115[test_integration.py]
    N116[test_issue_219_e2e.py]
    N117[test_language_detector.py]
    N118[test_llms_txt_detector.py]
    N119[test_llms_txt_downloader.py]
    N120[test_llms_txt_parser.py]
    N121[test_markdown_parsing.py]
    N122[test_mcp_fastmcp.py]
    N123[test_mcp_git_sources.py]
    N124[test_mcp_server.py]
    N125[test_merge_sources_github.py]
    N126[test_multi_source.py]
    N127[test_package_skill.py]
    N128[test_package_structure.py]
    N129[test_parallel_scraping.py]
    N130[test_pattern_recognizer.py]
    N131[test_pdf_advanced_features.py]
    N132[test_pdf_extractor.py]
    N133[test_pdf_scraper.py]
    N134[test_pr144_concerns.py]
    N135[test_quality_checker.py]
    N136[test_rate_limit_handler.py]
    N137[test_real_world_fastmcp.py]
    N138[test_scraper_features.py]
    N139[test_server_fastmcp_http.py]
    N140[test_setup_scripts.py]
    N141[test_skip_llms_txt.py]
    N142[test_smart_summarization.py]
    N143[test_source_manager.py]
    N144[test_swift_detection.py]
    N145[test_terminal_detection.py]
    N146[test_test_example_extractor.py]
    N147[test_unified.py]
    N148[test_unified_analyzer.py]
    N149[test_unified_mcp_integration.py]
    N150[test_upload_skill.py]
    N151[test_utilities.py]